### ISSUE TITLE
XCode build fails

### ISSUE THREAD

**Issue by devrafael-source** [yasirkula/UnityiOSFilePicker#2]
macOS Catalina - 10.15.3
Xcode 11.5(11E608c)

Undefined symbol: _kUTTagClassFilenameExtension
Undefined symbol: _UTTypeCreatePreferredIdentifierForTag

Both under convertExtensionToUTI function.

![image](https://user-images.githubusercontent.com/26442553/87354861-b2af6880-c535-11ea-9c9b-b68cb99750c9.png)

No error in the function itself:
![image](https://user-images.githubusercontent.com/26442553/87356232-189cef80-c538-11ea-8c71-18a58cfbfee2.png)

C#:
![image](https://user-images.githubusercontent.com/26442553/87356159-f99e5d80-c537-11ea-9782-c1a6ec5de322.png)

**Comment by yasirkula** [comment]
Did you follow the [Setup](https://github.com/yasirkula/UnityiOSFilePicker#setup) instructions? Note that Automated Setup is disabled by default (more info available in the link).

**Comment by devrafael-source** [comment]
Yes.

I tried the Automated Setup too, but:
![image](https://user-images.githubusercontent.com/26442553/87359851-21dd8a80-c53f-11ea-99bf-b6c7edc3d751.png)

**Comment by devrafael-source** [comment]
Tried without using ConvertExtensionToUTI in my C#, same error.

**Comment by yasirkula** [comment]
Error message says that your bundle identifier has invalid characters. Perhaps you put a comma, space or şğıüİ character there by mistake?

**Comment by devrafael-source** [comment]
Look likes the bundle is 'com.unity3d.frameworkdSPACEcom.company.appName'.
com.unity3d.frameworkd and com.company.appName are correct. 

Where did come from the SPACE between them?

I think that the Automated Setup generated this, because I never saw that specific error.
`pbxProject.AddBuildProperty( targetGUID, "PRODUCT_BUNDLE_IDENTIFIER", PlayerSettings.applicationIdentifier )`
But does not looks like that there is some space. In the Inspector, the first character of Application Identifier is 'c', not ' '.

**Comment by yasirkula** [comment]
Oh, perhaps there is another plugin that also calls AddBuildProperty with "com.unity3d.frameworkd". Since it is not SetBuildProperty, these 2 values are appended with a space between them. In your project, it is safe to comment out my AddBuildProperty line since the other plugin is already filling it.

**Comment by devrafael-source** [comment]
I removed `pbxProject.AddBuildProperty( targetGUID, "PRODUCT_BUNDLE_IDENTIFIER", PlayerSettings.applicationIdentifier )` and now it build fine.
